name: CI

on:
  push:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DISABLE_SPRING: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Prepare DB
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run RSpec
        run: bundle exec rspec --format progress
